
import com.WhoKnowsWhere.WhoKnowsWhere.model.TravelMethod;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.ExpenseDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.DestinationDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.RecommendationsResponseDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.RecommendationsRequestDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.RecommendationDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.model.RegisteredUser;
import com.WhoKnowsWhere.WhoKnowsWhere.model.DestinationType;
import com.WhoKnowsWhere.WhoKnowsWhere.model.Motivation;

global RecommendationsRequestDTO recommendationsRequestDTO;

rule "Increase recommendation rank destination type: Adventure, motivation: ENJOYING_NATURE"
	no-loop
	lock-on-active true
	when 
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type.contains(DestinationType.ADVENTURE)) from $dest
		$user: RegisteredUser(motivation == Motivation.ENJOYING_NATURE)
	then
		System.out.println("Increased rank by 20");
		modify($recommendation) {
			setRank($recommendation.getRank() + 20);
		}
	
end

rule "Increase recommendation rank destination type: Adventure with Car, motivation: ENJOYING_NATURE"
	no-loop
	lock-on-active true
	when 
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type.contains(DestinationType.ADVENTURE)) from $dest
		$user: RegisteredUser(motivation == Motivation.ENJOYING_NATURE)
		eval(recommendationsRequestDTO.getTravelMethod() == TravelMethod.CAR)
	then
		System.out.println("Increased rank by 5");
		modify($recommendation) {
			setRank($recommendation.getRank() + 5);
		}
	
end

rule "Increase recommendation rank destination type: Relaxation, motivation: ENJOYING_NATURE"
	no-loop
	lock-on-active true
	when 
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type.contains(DestinationType.RELAXATION)) from $dest
		$user: RegisteredUser(motivation == Motivation.ENJOYING_NATURE)
	then
		System.out.println("Increased rank by 10");
		modify($recommendation) {
			setRank($recommendation.getRank() + 10);
		}
	
end

rule "Increase recommendation rank destination type: Adventure, motivation: SEEKING_FUN"
	no-loop
	lock-on-active true
	when
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type.contains(DestinationType.URBAN)) from $dest
		$user: RegisteredUser(motivation == Motivation.SEEKING_FUN)
	then
		System.out.println("Increased rank by 6");
		modify($recommendation) {
			setRank($recommendation.getRank() + 6);
		}
	
end

rule "Increase recommendation rank destination type: Adventure, motivation: LEARNING_SOMETHING_NEW"
	no-loop
	lock-on-active true
	when 
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type.contains(DestinationType.ADVENTURE)) from $dest
		$user: RegisteredUser(motivation == Motivation.LEARNING_SOMETHING_NEW)
	then
		System.out.println("Increased rank by 2");
		modify($recommendation) {
			setRank($recommendation.getRank() + 2);
		}
	
end

rule "Increase recommendation rank destination type: Urban, motivation: LEARNING_SOMETHING_NEW"
	no-loop
	lock-on-active true
	when 
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type.contains(DestinationType.URBAN)) from $dest
		$user: RegisteredUser(motivation == Motivation.LEARNING_SOMETHING_NEW)
	then
		System.out.println("Increased rank by 15");
		modify($recommendation) {
			setRank($recommendation.getRank() + 15);
		}
	
end

rule "Increase recommendation rank destination type: Urban, motivation: ENJOYING_NATURE"
	no-loop
	lock-on-active true
	when 
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type.contains(DestinationType.URBAN)) from $dest
		$user: RegisteredUser(motivation == Motivation.ENJOYING_NATURE)
	then
		System.out.println("Decreased rank by 5");
		modify($recommendation) {
			setRank($recommendation.getRank() - 5);
		}
	
end