
import com.WhoKnowsWhere.WhoKnowsWhere.model.TravelMethod;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.ExpenseDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.DestinationDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.RecommendationsResponseDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.RecommendationsRequestDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.RecommendationDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.model.RegisteredUser;
import com.WhoKnowsWhere.WhoKnowsWhere.model.DestinationType;
import com.WhoKnowsWhere.WhoKnowsWhere.model.Motivation;

global RecommendationsRequestDTO recommendationsRequestDTO;

rule "Increase recommendation rank destination type: Adventure"
	no-loop
	lock-on-active true
	when 
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type == DestinationType.ADVENTURE) from $dest
		$user: RegisteredUser(motivation == Motivation.ENJOYING_NATURE)
	then
		System.out.println("Increased rank by 20");
		modify($recommendation) {
			setRank($recommendation.getRank() + 20);
		}
	
end

rule "Increase recommendation rank destination type: Adventure with Car"
	no-loop
	lock-on-active true
	when 
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type == DestinationType.ADVENTURE) from $dest
		$user: RegisteredUser(motivation == Motivation.ENJOYING_NATURE)
		eval(recommendationsRequestDTO.getTravelMethod() == TravelMethod.CAR)
	then
		System.out.println("Increased rank by 5");
		modify($recommendation) {
			setRank($recommendation.getRank() + 5);
		}
	
end

rule "Increase recommendation rank destination type: Relaxation"
	no-loop
	lock-on-active true
	when 
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type == DestinationType.RELAXATION) from $dest
		$user: RegisteredUser(motivation == Motivation.ENJOYING_NATURE)
	then
		System.out.println("Increased rank by 10");
		modify($recommendation) {
			setRank($recommendation.getRank() + 10);
		}
	
end