
import com.WhoKnowsWhere.WhoKnowsWhere.model.TravelMethod;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.ExpenseDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.DestinationDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.RecommendationsResponseDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.RecommendationsRequestDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.dto.RecommendationDTO;
import com.WhoKnowsWhere.WhoKnowsWhere.model.RegisteredUser;
import com.WhoKnowsWhere.WhoKnowsWhere.model.DestinationType;
import com.WhoKnowsWhere.WhoKnowsWhere.model.Motivation;

global RecommendationsRequestDTO recommendationsRequestDTO;



rule "Increase recommendation rank destination type: URBAN, status: STUDENT"
	no-loop
	lock-on-active true
	when
		$recommendation: RecommendationDTO($dest: destination)
		DestinationDTO(type.contains(DestinationType.URBAN)) from $dest
		$user: RegisteredUser(userStatus == UserStatus.STUDENT)
	then
		System.out.println("Increased rank by 6");
		modify($recommendation) {
			setRank($recommendation.getRank() + 6);
		}

end